version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit-con:
    image: my-rabbit:1.1.5
    depends_on:
      rabbitmq:
        condition: service_started